CC = gcc

all: client

client: main.o initSocket.o closeSocket.o findMouseCoordinates.o
	$(CC) main.o initSocket.o closeSocket.o findMouseCoordinates.o -o client

main.o: main.c
	$(CC) main.c

initSocket.o: initSocket.c
	$(CC) initSocket.c

closeSocket.o: closeSocket.c
	$(CC) closeSocket.c

findMouseCoordinates.o: findMouseCoordinates.c
	$(CC) findMouseCoordinates.c

clean:
	rm -rf *.o client